// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       int    `json:"id"`
	PostID   int    `json:"postId"`
	Author   string `json:"author"`
	Content  string `json:"content"`
	ParentID *int   `json:"parentId,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID              int        `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	Comments        []*Comment `json:"comments,omitempty"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	Author          string     `json:"author"`
}

type Query struct {
}

type Subscription struct {
}
